version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    restart: unless-stopped
