name: Node.js CI

on:
  push:
    branches:
      - dev-test
  pull_request:
    branches:
      - dev-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Run tests
      run: npm test
