name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: self-hosted
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USERNAME: ${{ secrets.REMOTE_USERNAME }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to production
        run: |
          sudo docker rm -f newcont
          sudo docker rmi -f newimg
          sudo docker build -t newimg .
          sudo docker run -itd --name=newcont -p "3012:3000" newimg
          
      - name: Build and Push Docker Image
        env:
          NEXUS_REGISTRY: your-nexus-registry-url
          IMAGE_NAME: your-image-name
        run: |
          echo ${{ secrets.NEXUS_PASSWORD }} | docker login -u ${{ secrets.NEXUS_USERNAME }} --password-stdin $NEXUS_REGISTRY
          docker buildx create --use
          docker buildx build --push --platform linux --tag $NEXUS_REGISTRY/$IMAGE_NAME:latest .
